run:
  timeout: 5m
  go: "1.23"

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - bodyclose
    - gosec
    - misspell
    - unconvert
    - unparam

linters-settings:
  gosec:
    excludes:
      - G104 # unhandled errors (we handle selectively)

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - errcheck
